### ISSUE TITLE
Z_BUF_ERROR

### ISSUE THREAD

**Issue by dkurt** [actions/download-artifact#53]
Hi! There is an error after upgrade to `actions-runner-linux-arm-2.272.0` at `actions/download-artifact@v2` stage:

```
Total file count: 2 ---- Processed file #0 (0.0%)
Total file count: 2 ---- Processed file #0 (0.0%)
Total file count: 2 ---- Processed file #0 (0.0%)
Total file count: 2 ---- Processed file #0 (0.0%)
Total file count: 2 ---- Processed file #0 (0.0%)
Total file count: 2 ---- Processed file #0 (0.0%)
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (zlib.js:170:17)
Emitted 'error' event on Gunzip instance at:
    at Zlib.zlibOnError [as onerror] (zlib.js:173:8) {
  errno: -5,
  code: 'Z_BUF_ERROR'
}
```

**Comment by dkurt** [comment]
solved in the next scheduled workflow
