### ISSUE TITLE
Z_BUF_ERROR on large Docker images after two minutes of being stalled

### ISSUE THREAD

**Issue by WyriHaximus** [actions/download-artifact#55]
Using Github Actions to build Docker images. Until now it was just alpine images but I also want to create debian based images as well. Those images are significantly bigger and as such it takes longer to upload them as an artifact. These images are needing 4GB in size and at this point have a 100% fail rate.

Link to the logs: https://github.com/WyriHaximusNet/docker-php/runs/973243081?check_suite_focus=true#step:4:217
Raw logs:
```
2020-08-11T21:39:57.0777951Z shell: /bin/bash -e {0}
2020-08-11T21:39:57.0778133Z env:
2020-08-11T21:39:57.0778273Z   DOCKER_IMAGE: wyrihaximusnet/php
2020-08-11T21:39:57.0778401Z   DOCKER_BUILDKIT: 1
2020-08-11T21:39:57.0778533Z ##[endgroup]
2020-08-11T21:39:57.1053333Z   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
2020-08-11T21:39:57.1055891Z                                  Dload  Upload   Total   Spent    Left  Speed
2020-08-11T21:39:57.1058114Z 
2020-08-11T21:39:57.1339680Z   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
2020-08-11T21:39:57.1342375Z 100   636  100   636    0     0  28909      0 --:--:-- --:--:-- --:--:-- 28909
2020-08-11T21:39:57.2466546Z 
2020-08-11T21:39:57.2471653Z 100 9631k  100 9631k    0     0  66.7M      0 --:--:-- --:--:-- --:--:-- 66.7M
2020-08-11T21:39:57.2644972Z ##[group]Run actions/download-artifact@v2
2020-08-11T21:39:57.2645158Z with:
2020-08-11T21:39:57.2645277Z   name: docker-image-zts-zts-7.2-debian-buster-buster
2020-08-11T21:39:57.2645392Z   path: ./docker-image
2020-08-11T21:39:57.2645629Z env:
2020-08-11T21:39:57.2645739Z   DOCKER_IMAGE: wyrihaximusnet/php
2020-08-11T21:39:57.2646008Z   DOCKER_BUILDKIT: 1
2020-08-11T21:39:57.2646096Z ##[endgroup]
2020-08-11T21:39:57.3162022Z Starting download for docker-image-zts-zts-7.2-debian-buster-buster
2020-08-11T21:39:57.4899696Z Directory structure has been setup for the artifact
2020-08-11T21:39:57.4902004Z Total number of files that will be downloaded: 2
2020-08-11T21:39:58.5764113Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:40:00.0779400Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:40:00.4904782Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:40:01.4906038Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:40:02.4916714Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:40:03.4904233Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:40:04.4903744Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:40:05.4903670Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:40:06.4909034Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:40:07.4922752Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:40:08.4918993Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:40:09.4918001Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:40:10.4913830Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:40:11.4914718Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:40:12.4923225Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:40:13.4920997Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:40:14.4919687Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:40:15.4951356Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:40:16.4935968Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:40:17.4924684Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:40:18.4925761Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:40:19.4925567Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:40:20.4936529Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:40:21.4936511Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:40:22.4941829Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:40:23.4978986Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:40:24.4933672Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:40:25.4933449Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:40:26.4938388Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:40:27.4932836Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:40:28.4935559Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:40:29.4933681Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:40:30.4941626Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:40:31.4932980Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:40:32.4939034Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:40:33.4933397Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:40:34.4933140Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:40:35.4932911Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:40:36.4934796Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:40:37.4932224Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:40:38.4934869Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:40:39.4934086Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:40:40.4932834Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:40:41.4932245Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:40:42.4932812Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:40:43.4933510Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:40:44.4938049Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:40:45.4933056Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:40:46.4941976Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:40:47.4933578Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:40:48.4938779Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:40:49.4933501Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:40:50.4933156Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:40:51.4932703Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:40:52.4934229Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:40:53.4932286Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:40:54.4939427Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:40:55.4938235Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:40:56.4932843Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:40:57.4933654Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:40:58.4932692Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:40:59.4933883Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:41:00.4949286Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:41:01.4948475Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:41:02.4952259Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:41:03.4958722Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:41:04.4953325Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:41:05.4952838Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:41:06.4965376Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:41:07.4978917Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:41:08.4992608Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:41:09.5006227Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:41:10.5011437Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:41:11.5014127Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:41:12.5027756Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:41:13.5041395Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:41:14.5044670Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:41:15.5059356Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:41:16.5073195Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:41:17.5086940Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:41:18.5092171Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:41:19.5104762Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:41:20.5116841Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:41:21.5129158Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:41:22.5141266Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:41:23.5154293Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:41:24.5166472Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:41:25.5179389Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:41:26.5182995Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:41:27.5184321Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:41:28.5196407Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:41:29.5209433Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:41:30.5221337Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:41:31.5234172Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:41:32.5246761Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:41:33.5258765Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:41:34.5271014Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:41:35.5274753Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:41:36.5296657Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:41:37.5299986Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:41:38.5311864Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:41:39.5313832Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:41:40.5327411Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:41:41.5339088Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:41:42.5351118Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:41:43.5354519Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:41:44.5366958Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:41:45.5379869Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:41:46.5392289Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:41:47.5396590Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:41:48.5408589Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:41:49.5421279Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:41:50.5434512Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:41:51.5448988Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:41:53.1085651Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:41:53.5473106Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:41:54.5485705Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:41:55.5498128Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:41:57.1097414Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:41:57.5521456Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:41:58.5533988Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:41:59.5548795Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:42:00.5560274Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:42:01.5572408Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:42:02.5575362Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:42:03.5587588Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:42:04.5600146Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:42:05.5613336Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:42:06.5615760Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:42:07.5628951Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:42:08.5641893Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:42:09.5654112Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:42:10.5666278Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:42:11.5678714Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:42:12.5690815Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:42:13.5702492Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:42:14.5715101Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:42:15.5728465Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:42:16.5740930Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:42:17.5753927Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:42:18.5765764Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:42:19.5778338Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:42:20.5790948Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:42:21.5803198Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:42:22.5815230Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:42:23.5821178Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:42:24.5825165Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:42:25.5837763Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:42:26.5849585Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:42:27.5863682Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:42:28.5866854Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:42:29.5878551Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:42:31.1191555Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:42:31.5894527Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:42:32.5908115Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:42:33.5920167Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:42:34.5932497Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:42:35.5936618Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:42:36.5947897Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:42:37.5959928Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:42:38.5973610Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:42:39.5985307Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:42:40.6000876Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:42:41.6012347Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:42:42.6024818Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:42:43.6037394Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:42:44.6049813Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:42:45.6061235Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:42:46.6064005Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:42:47.6076484Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:42:48.6080490Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:42:49.6092709Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:42:50.6101175Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:42:51.6113692Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:42:52.6126064Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:42:53.6138787Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:42:54.6151283Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:42:55.6164205Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:42:56.6177591Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:42:57.6181314Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:42:58.6194497Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:42:59.6206510Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:43:00.6218842Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:43:01.6232363Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:43:02.6234261Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:43:03.6246572Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:43:04.6251259Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:43:05.6264740Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:43:06.6276784Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:43:07.6289168Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:43:08.6301933Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:43:10.1307213Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:43:10.6316949Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:43:11.6331857Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:43:12.6333550Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:43:13.6336348Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:43:14.6349482Z Total file count: 2 ---- Processed file #1 (50.0%)
2020-08-11T21:43:15.3322944Z events.js:187
2020-08-11T21:43:15.3323908Z       throw er; // Unhandled 'error' event
2020-08-11T21:43:15.3324079Z       ^
2020-08-11T21:43:15.3324122Z 
2020-08-11T21:43:15.3324563Z Error: unexpected end of file
2020-08-11T21:43:15.3324845Z     at Zlib.zlibOnError [as onerror] (zlib.js:170:17)
2020-08-11T21:43:15.3325319Z Emitted 'error' event on Gunzip instance at:
2020-08-11T21:43:15.3325605Z     at Zlib.zlibOnError [as onerror] (zlib.js:173:8) {
2020-08-11T21:43:15.3325824Z   errno: -5,
2020-08-11T21:43:15.3326024Z   code: 'Z_BUF_ERROR'
2020-08-11T21:43:15.3326106Z }
2020-08-11T21:43:15.3441578Z ##[group]Run exit 0
2020-08-11T21:43:15.3441749Z [36;1mexit 0[0m
```

**Comment by m-kuhn** [comment]
Same here, downloading 4 files, ~450 MB each

**Comment by konradpabjan** [comment]
This specific error has been fixed. The latest update in `v2` will retry if a partial download is encountered. There are still some scenarios where we don't always retry (I am working on a fix), but this specific `Zlib.zlibOnError` error should be no more.
